apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: observability
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.sre-copilot.localtest.me`)
      kind: Rule
      services:
        - name: grafana
          port: 80
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: observability
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.sre-copilot.localtest.me`)
      kind: Rule
      services:
        - name: prometheus-server
          port: 80
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.sre-copilot.localtest.me`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
          scheme: https
  tls: {}
