apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ollama-externalname
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalName }}
  ports:
    - name: ollama
      port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
