---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: sre-copilot
spec:
  encryptedData:
    ANOMALY_INJECTOR_TOKEN: AgCGNXPZLlFr+2qZgb9O+HoA8j0p9WjRRyIm0ejLC/NXn0gkCHd1YBAdUYlam7FurQanpz1YYevh0Z/KPy/fJpjOvU0aeXDsuiq8/QqfyCN/63cXcgPugkAOLAdhJbTLXbrMnUYXE0RiTnF37b7It5JT4Bh03PDy5LYAToKsmBZPXMvLuNiyf3f9lZsk4+P3I56XZrJJmv98E1fQ/QVt+c4gafGN5eKWNJ6ub0sdv36PD5T9Cst7CmuikO7qikQ/576KXZTZgnmKLi827WqX0r6VgkBbksVDip/FCsHqdhdYt5RHYGs/9iwElO5OnAKMeTyTCiS8OUjU/iTLYfxDyCq/DCC0T9B0aFWPknU7vgyzkDh5qtmj8U2M5g5NUo9fqiS3qkEjmJ0V3MZFt/ZLF0S0h0sEFTxoKIPHoDbvpXmd7gLVBMO0+OI0Z8d5svmAhUhOtEcwIZZ5LhHU4iaK+FWjHCBG2jJLDfCoZw9bmliSKZ+HFHP1ApnQUn/BZglcg5lNhNvp1l3eX2svbvFrf7XsdM648Nt5ihnh0QJDq2Z7fD5sLw9cLXV5o2Hc2zKJseGydrBBDqyQkX8ZDaClEwDePupc80nUBGhEzCyf0uC3aYexNewaOlv8QZ2TA1Gyaf46CWUFjngO5DHyjyChO0p7l9bF8CbSaRQWxswZ2vkTgCeLYfixKBnfw72T5GtCerW3PRWxcIaohnwqtKJtc9z6u2Kz6ce2Lo2HkzZ+us267GrjRZXRoZ/PWKR+hvtn1RO16PttllSNsqioSByjSecC
  template:
    metadata:
      name: backend-secrets
      namespace: sre-copilot
